# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DlgHypChecher.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DlgHypChecker(object):
    def setupUi(self, DlgHypChecker):
        DlgHypChecker.setObjectName("DlgHypChecker")
        DlgHypChecker.resize(822, 645)
        self.gridLayout_2 = QtWidgets.QGridLayout(DlgHypChecker)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(DlgHypChecker)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 196, 525))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btClose = QtWidgets.QPushButton(DlgHypChecker)
        self.btClose.setObjectName("btClose")
        self.horizontalLayout.addWidget(self.btClose)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(DlgHypChecker)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(DlgHypChecker)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(DlgHypChecker)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.toolButton = QtWidgets.QToolButton(DlgHypChecker)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(DlgHypChecker)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(DlgHypChecker)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_3.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(DlgHypChecker)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_3.addWidget(self.toolButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lblNetResponse = QtWidgets.QLabel(DlgHypChecker)
        self.lblNetResponse.setObjectName("lblNetResponse")
        self.verticalLayout.addWidget(self.lblNetResponse)
        self.edResp = QtWidgets.QPlainTextEdit(DlgHypChecker)
        self.edResp.setPlainText("")
        self.edResp.setObjectName("edResp")
        self.verticalLayout.addWidget(self.edResp)
        self.label_2 = QtWidgets.QLabel(DlgHypChecker)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.edHyp = QtWidgets.QPlainTextEdit(DlgHypChecker)
        self.edHyp.setObjectName("edHyp")
        self.verticalLayout.addWidget(self.edHyp)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(4, 5)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(DlgHypChecker)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.lblHyp = QtWidgets.QLabel(DlgHypChecker)
        self.lblHyp.setObjectName("lblHyp")
        self.gridLayout.addWidget(self.lblHyp, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(DlgHypChecker)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DlgHypChecker)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tbFilter = QtWidgets.QToolButton(DlgHypChecker)
        self.tbFilter.setObjectName("tbFilter")
        self.horizontalLayout_5.addWidget(self.tbFilter)
        self.tbPredict = QtWidgets.QToolButton(DlgHypChecker)
        self.tbPredict.setObjectName("tbPredict")
        self.horizontalLayout_5.addWidget(self.tbPredict)
        self.tbHyp = QtWidgets.QToolButton(DlgHypChecker)
        self.tbHyp.setObjectName("tbHyp")
        self.horizontalLayout_5.addWidget(self.tbHyp)
        self.tbDict = QtWidgets.QToolButton(DlgHypChecker)
        self.tbDict.setObjectName("tbDict")
        self.horizontalLayout_5.addWidget(self.tbDict)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 200)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(DlgHypChecker)
        QtCore.QMetaObject.connectSlotsByName(DlgHypChecker)

    def retranslateUi(self, DlgHypChecker):
        _translate = QtCore.QCoreApplication.translate
        DlgHypChecker.setWindowTitle(_translate("DlgHypChecker", "Проверка гипотез"))
        self.btClose.setText(_translate("DlgHypChecker", "Закрыть"))
        self.label_7.setText(_translate("DlgHypChecker", "????"))
        self.label_4.setText(_translate("DlgHypChecker", "Таблица вариантов объединения"))
        self.label_6.setText(_translate("DlgHypChecker", "Отсеить комбинации"))
        self.toolButton.setText(_translate("DlgHypChecker", "по расстоянию"))
        self.toolButton_2.setText(_translate("DlgHypChecker", "по размеру"))
        self.toolButton_3.setText(_translate("DlgHypChecker", "наклону?"))
        self.toolButton_4.setText(_translate("DlgHypChecker", "отменить"))
        self.lblNetResponse.setText(_translate("DlgHypChecker", "Отклик сети"))
        self.label_2.setText(_translate("DlgHypChecker", "Гипотезы"))
        self.label_5.setText(_translate("DlgHypChecker", "Последовательность: Е[2] С Т Ь В Р Е[2] М Е[3] НА"))
        self.lblHyp.setText(_translate("DlgHypChecker", "????"))
        self.label.setText(_translate("DlgHypChecker", "Результирующая гипотеза"))
        self.label_3.setText(_translate("DlgHypChecker", "Вывод"))
        self.tbFilter.setText(_translate("DlgHypChecker", "1. отфильтровать"))
        self.tbPredict.setText(_translate("DlgHypChecker", "2.отклик сети"))
        self.tbHyp.setText(_translate("DlgHypChecker", "3.гипотез сегментов"))
        self.tbDict.setText(_translate("DlgHypChecker", "4.словарь"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgHypChecker = QtWidgets.QDialog()
    ui = Ui_DlgHypChecker()
    ui.setupUi(DlgHypChecker)
    DlgHypChecker.show()
    sys.exit(app.exec_())

