# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.tbMuLineUp = QtWidgets.QToolButton(self.centralwidget)
        self.tbMuLineUp.setObjectName("tbMuLineUp")
        self.horizontalLayout_4.addWidget(self.tbMuLineUp)
        self.tbMuLineDown = QtWidgets.QToolButton(self.centralwidget)
        self.tbMuLineDown.setObjectName("tbMuLineDown")
        self.horizontalLayout_4.addWidget(self.tbMuLineDown)
        self.tbExcludeBoxes = QtWidgets.QToolButton(self.centralwidget)
        self.tbExcludeBoxes.setObjectName("tbExcludeBoxes")
        self.horizontalLayout_4.addWidget(self.tbExcludeBoxes)
        self.tbLineNew = QtWidgets.QToolButton(self.centralwidget)
        self.tbLineNew.setObjectName("tbLineNew")
        self.horizontalLayout_4.addWidget(self.tbLineNew)
        self.tbLineDel = QtWidgets.QToolButton(self.centralwidget)
        self.tbLineDel.setObjectName("tbLineDel")
        self.horizontalLayout_4.addWidget(self.tbLineDel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tb1b1c = QtWidgets.QToolButton(self.centralwidget)
        self.tb1b1c.setObjectName("tb1b1c")
        self.horizontalLayout_2.addWidget(self.tb1b1c)
        self.tb2b1c = QtWidgets.QToolButton(self.centralwidget)
        self.tb2b1c.setObjectName("tb2b1c")
        self.horizontalLayout_2.addWidget(self.tb2b1c)
        self.tb3b1c = QtWidgets.QToolButton(self.centralwidget)
        self.tb3b1c.setObjectName("tb3b1c")
        self.horizontalLayout_2.addWidget(self.tb3b1c)
        self.tb1b2c = QtWidgets.QToolButton(self.centralwidget)
        self.tb1b2c.setObjectName("tb1b2c")
        self.horizontalLayout_2.addWidget(self.tb1b2c)
        self.tb1b3c = QtWidgets.QToolButton(self.centralwidget)
        self.tb1b3c.setObjectName("tb1b3c")
        self.horizontalLayout_2.addWidget(self.tb1b3c)
        self.tb3b2c = QtWidgets.QToolButton(self.centralwidget)
        self.tb3b2c.setObjectName("tb3b2c")
        self.horizontalLayout_2.addWidget(self.tb3b2c)
        self.tb0b1c = QtWidgets.QToolButton(self.centralwidget)
        self.tb0b1c.setObjectName("tb0b1c")
        self.horizontalLayout_2.addWidget(self.tb0b1c)
        self.tb1b0c = QtWidgets.QToolButton(self.centralwidget)
        self.tb1b0c.setObjectName("tb1b0c")
        self.horizontalLayout_2.addWidget(self.tb1b0c)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.edNBox = QtWidgets.QSpinBox(self.centralwidget)
        self.edNBox.setProperty("value", 2)
        self.edNBox.setObjectName("edNBox")
        self.horizontalLayout_2.addWidget(self.edNBox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.edNChar = QtWidgets.QSpinBox(self.centralwidget)
        self.edNChar.setProperty("value", 2)
        self.edNChar.setObjectName("edNChar")
        self.horizontalLayout_2.addWidget(self.edNChar)
        self.tbChange = QtWidgets.QToolButton(self.centralwidget)
        self.tbChange.setObjectName("tbChange")
        self.horizontalLayout_2.addWidget(self.tbChange)
        self.tbSplit = QtWidgets.QToolButton(self.centralwidget)
        self.tbSplit.setObjectName("tbSplit")
        self.horizontalLayout_2.addWidget(self.tbSplit)
        self.tbUnite = QtWidgets.QToolButton(self.centralwidget)
        self.tbUnite.setObjectName("tbUnite")
        self.horizontalLayout_2.addWidget(self.tbUnite)
        self.tbTrimUnused = QtWidgets.QToolButton(self.centralwidget)
        self.tbTrimUnused.setEnabled(False)
        self.tbTrimUnused.setObjectName("tbTrimUnused")
        self.horizontalLayout_2.addWidget(self.tbTrimUnused)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edLine = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edLine.setFont(font)
        self.edLine.setText("")
        self.edLine.setObjectName("edLine")
        self.horizontalLayout_3.addWidget(self.edLine)
        self.tbLineUpdate = QtWidgets.QToolButton(self.centralwidget)
        self.tbLineUpdate.setObjectName("tbLineUpdate")
        self.horizontalLayout_3.addWidget(self.tbLineUpdate)
        self.tbLineSet = QtWidgets.QToolButton(self.centralwidget)
        self.tbLineSet.setObjectName("tbLineSet")
        self.horizontalLayout_3.addWidget(self.tbLineSet)
        self.tbEditText = QtWidgets.QToolButton(self.centralwidget)
        self.tbEditText.setEnabled(True)
        self.tbEditText.setObjectName("tbEditText")
        self.horizontalLayout_3.addWidget(self.tbEditText)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 968, 537))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnExtractLetters = QtWidgets.QPushButton(self.centralwidget)
        self.btnExtractLetters.setObjectName("btnExtractLetters")
        self.horizontalLayout.addWidget(self.btnExtractLetters)
        self.btnFindLetters = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindLetters.setObjectName("btnFindLetters")
        self.horizontalLayout.addWidget(self.btnFindLetters)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.isExtended = QtWidgets.QCheckBox(self.centralwidget)
        self.isExtended.setText("")
        self.isExtended.setObjectName("isExtended")
        self.horizontalLayout.addWidget(self.isExtended)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.cbDpiFrom = QtWidgets.QComboBox(self.centralwidget)
        self.cbDpiFrom.setEditable(True)
        self.cbDpiFrom.setObjectName("cbDpiFrom")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.cbDpiFrom.addItem("")
        self.horizontalLayout.addWidget(self.cbDpiFrom)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.cbDpiTo = QtWidgets.QComboBox(self.centralwidget)
        self.cbDpiTo.setEditable(True)
        self.cbDpiTo.setObjectName("cbDpiTo")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.cbDpiTo.addItem("")
        self.horizontalLayout.addWidget(self.cbDpiTo)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setTearOffEnabled(False)
        self.menu.setObjectName("menu")
        self.menu_5 = QtWidgets.QMenu(self.menu)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menu)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menu)
        self.menu_7.setObjectName("menu_7")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actOpenAndProcessImage = QtWidgets.QAction(MainWindow)
        self.actOpenAndProcessImage.setObjectName("actOpenAndProcessImage")
        self.actOpenText = QtWidgets.QAction(MainWindow)
        self.actOpenText.setObjectName("actOpenText")
        self.actOpenMarkup = QtWidgets.QAction(MainWindow)
        self.actOpenMarkup.setObjectName("actOpenMarkup")
        self.actSaveImage = QtWidgets.QAction(MainWindow)
        self.actSaveImage.setObjectName("actSaveImage")
        self.actSaveBbox = QtWidgets.QAction(MainWindow)
        self.actSaveBbox.setObjectName("actSaveBbox")
        self.actSaveText = QtWidgets.QAction(MainWindow)
        self.actSaveText.setObjectName("actSaveText")
        self.actSaveMarkup = QtWidgets.QAction(MainWindow)
        self.actSaveMarkup.setObjectName("actSaveMarkup")
        self.actExit = QtWidgets.QAction(MainWindow)
        self.actExit.setObjectName("actExit")
        self.actChange1b1c = QtWidgets.QAction(MainWindow)
        self.actChange1b1c.setObjectName("actChange1b1c")
        self.actChange2b1c = QtWidgets.QAction(MainWindow)
        self.actChange2b1c.setObjectName("actChange2b1c")
        self.actChange3b1c = QtWidgets.QAction(MainWindow)
        self.actChange3b1c.setObjectName("actChange3b1c")
        self.actChange1b2c = QtWidgets.QAction(MainWindow)
        self.actChange1b2c.setObjectName("actChange1b2c")
        self.actChange1b3c = QtWidgets.QAction(MainWindow)
        self.actChange1b3c.setObjectName("actChange1b3c")
        self.actTextLineSet = QtWidgets.QAction(MainWindow)
        self.actTextLineSet.setObjectName("actTextLineSet")
        self.actTextLineUpdate = QtWidgets.QAction(MainWindow)
        self.actTextLineUpdate.setObjectName("actTextLineUpdate")
        self.actTextEdit = QtWidgets.QAction(MainWindow)
        self.actTextEdit.setObjectName("actTextEdit")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_box_char = QtWidgets.QAction(MainWindow)
        self.action_box_char.setObjectName("action_box_char")
        self.action_box_char_2 = QtWidgets.QAction(MainWindow)
        self.action_box_char_2.setObjectName("action_box_char_2")
        self.actShowPageBase = QtWidgets.QAction(MainWindow)
        self.actShowPageBase.setObjectName("actShowPageBase")
        self.actMarkupDefault = QtWidgets.QAction(MainWindow)
        self.actMarkupDefault.setObjectName("actMarkupDefault")
        self.actOpenBbox = QtWidgets.QAction(MainWindow)
        self.actOpenBbox.setObjectName("actOpenBbox")
        self.actSkipBoxLine = QtWidgets.QAction(MainWindow)
        self.actSkipBoxLine.setObjectName("actSkipBoxLine")
        self.actSkipTextLine = QtWidgets.QAction(MainWindow)
        self.actSkipTextLine.setObjectName("actSkipTextLine")
        self.actOpenImage = QtWidgets.QAction(MainWindow)
        self.actOpenImage.setObjectName("actOpenImage")
        self.actMuLineUp = QtWidgets.QAction(MainWindow)
        self.actMuLineUp.setObjectName("actMuLineUp")
        self.actMuLineDown = QtWidgets.QAction(MainWindow)
        self.actMuLineDown.setObjectName("actMuLineDown")
        self.actSaveSymbols = QtWidgets.QAction(MainWindow)
        self.actSaveSymbols.setObjectName("actSaveSymbols")
        self.actSelToUpLine = QtWidgets.QAction(MainWindow)
        self.actSelToUpLine.setObjectName("actSelToUpLine")
        self.actSelToDownLine = QtWidgets.QAction(MainWindow)
        self.actSelToDownLine.setObjectName("actSelToDownLine")
        self.actSelExclude = QtWidgets.QAction(MainWindow)
        self.actSelExclude.setObjectName("actSelExclude")
        self.actSelToNewLine = QtWidgets.QAction(MainWindow)
        self.actSelToNewLine.setObjectName("actSelToNewLine")
        self.actDelLine = QtWidgets.QAction(MainWindow)
        self.actDelLine.setObjectName("actDelLine")
        self.actPathConvertMkpSmp = QtWidgets.QAction(MainWindow)
        self.actPathConvertMkpSmp.setObjectName("actPathConvertMkpSmp")
        self.actCheckHyp = QtWidgets.QAction(MainWindow)
        self.actCheckHyp.setObjectName("actCheckHyp")
        self.actBuildStatistics = QtWidgets.QAction(MainWindow)
        self.actBuildStatistics.setObjectName("actBuildStatistics")
        self.menu_5.addAction(self.actSaveImage)
        self.menu_5.addAction(self.actSaveBbox)
        self.menu_5.addAction(self.actSaveText)
        self.menu_6.addAction(self.actOpenBbox)
        self.menu_6.addAction(self.actOpenText)
        self.menu_7.addAction(self.actPathConvertMkpSmp)
        self.menu.addAction(self.actOpenImage)
        self.menu.addAction(self.actOpenAndProcessImage)
        self.menu.addAction(self.actOpenMarkup)
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actSaveMarkup)
        self.menu.addAction(self.actSaveSymbols)
        self.menu.addAction(self.actShowPageBase)
        self.menu.addAction(self.menu_7.menuAction())
        self.menu.addAction(self.menu_5.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actExit)
        self.menu_2.addAction(self.actChange1b1c)
        self.menu_2.addAction(self.actChange2b1c)
        self.menu_2.addAction(self.actChange3b1c)
        self.menu_2.addAction(self.actChange1b2c)
        self.menu_2.addAction(self.actChange1b3c)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_box_char)
        self.menu_2.addAction(self.action_box_char_2)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actSkipBoxLine)
        self.menu_2.addAction(self.actSkipTextLine)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actMuLineUp)
        self.menu_2.addAction(self.actMuLineDown)
        self.menu_3.addAction(self.actSelToUpLine)
        self.menu_3.addAction(self.actSelToDownLine)
        self.menu_3.addAction(self.actSelExclude)
        self.menu_3.addAction(self.actSelToNewLine)
        self.menu_3.addAction(self.actDelLine)
        self.menu_4.addAction(self.actTextEdit)
        self.menu_4.addAction(self.actTextLineUpdate)
        self.menu_4.addAction(self.actTextLineSet)
        self.menu_8.addAction(self.actCheckHyp)
        self.menu_8.addSeparator()
        self.menu_8.addAction(self.actBuildStatistics)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())

        self.retranslateUi(MainWindow)
        self.cbDpiFrom.setCurrentIndex(4)
        self.cbDpiTo.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PageMarker"))
        self.label.setText(_translate("MainWindow", "ЛИНИИ"))
        self.tbMuLineUp.setToolTip(_translate("MainWindow", "Переместить выделенные области в верхнюю линию"))
        self.tbMuLineUp.setText(_translate("MainWindow", "up"))
        self.tbMuLineDown.setToolTip(_translate("MainWindow", "Переместить выделенные области в нижнюю линию"))
        self.tbMuLineDown.setText(_translate("MainWindow", "down"))
        self.tbExcludeBoxes.setToolTip(_translate("MainWindow", "Исключить выделенные области"))
        self.tbExcludeBoxes.setText(_translate("MainWindow", "excl"))
        self.tbLineNew.setToolTip(_translate("MainWindow", "Добавить выделенные элементы в новую линию"))
        self.tbLineNew.setText(_translate("MainWindow", "as new line"))
        self.tbLineDel.setToolTip(_translate("MainWindow", "Удалить линию"))
        self.tbLineDel.setText(_translate("MainWindow", "del line"))
        self.label_2.setText(_translate("MainWindow", "БОКСЫ"))
        self.tb1b1c.setText(_translate("MainWindow", "1b1c"))
        self.tb2b1c.setText(_translate("MainWindow", "2b1c"))
        self.tb3b1c.setText(_translate("MainWindow", "3b1c"))
        self.tb1b2c.setText(_translate("MainWindow", "1b2c"))
        self.tb1b3c.setText(_translate("MainWindow", "1b3c"))
        self.tb3b2c.setText(_translate("MainWindow", "3b2c"))
        self.tb0b1c.setText(_translate("MainWindow", "0b1c"))
        self.tb1b0c.setText(_translate("MainWindow", "1b0c"))
        self.label_3.setText(_translate("MainWindow", "box"))
        self.label_4.setText(_translate("MainWindow", "char"))
        self.tbChange.setToolTip(_translate("MainWindow", "Применить разметку к области"))
        self.tbChange.setText(_translate("MainWindow", "change"))
        self.tbSplit.setToolTip(_translate("MainWindow", "Отделить слева часть области (box,char)"))
        self.tbSplit.setText(_translate("MainWindow", "split"))
        self.tbUnite.setToolTip(_translate("MainWindow", "Объединить box областей"))
        self.tbUnite.setText(_translate("MainWindow", "unite"))
        self.tbTrimUnused.setToolTip(_translate("MainWindow", "Удалить неиспользуемые области"))
        self.tbTrimUnused.setText(_translate("MainWindow", "trimunused"))
        self.tbLineUpdate.setText(_translate("MainWindow", "upd"))
        self.tbLineSet.setText(_translate("MainWindow", "=>"))
        self.tbEditText.setText(_translate("MainWindow", "текст"))
        self.btnExtractLetters.setText(_translate("MainWindow", "Сохранить символы"))
        self.btnFindLetters.setText(_translate("MainWindow", "Проверить символы"))
        self.label_8.setText(_translate("MainWindow", "Включить контур у букв"))
        self.label_5.setText(_translate("MainWindow", "Рисунок исходный"))
        self.cbDpiFrom.setItemText(0, _translate("MainWindow", "72"))
        self.cbDpiFrom.setItemText(1, _translate("MainWindow", "100"))
        self.cbDpiFrom.setItemText(2, _translate("MainWindow", "150"))
        self.cbDpiFrom.setItemText(3, _translate("MainWindow", "200"))
        self.cbDpiFrom.setItemText(4, _translate("MainWindow", "300"))
        self.cbDpiFrom.setItemText(5, _translate("MainWindow", "400"))
        self.cbDpiFrom.setItemText(6, _translate("MainWindow", "600"))
        self.cbDpiFrom.setItemText(7, _translate("MainWindow", "1200"))
        self.label_6.setText(_translate("MainWindow", "конечный"))
        self.cbDpiTo.setItemText(0, _translate("MainWindow", "72"))
        self.cbDpiTo.setItemText(1, _translate("MainWindow", "100"))
        self.cbDpiTo.setItemText(2, _translate("MainWindow", "150"))
        self.cbDpiTo.setItemText(3, _translate("MainWindow", "200"))
        self.cbDpiTo.setItemText(4, _translate("MainWindow", "300"))
        self.cbDpiTo.setItemText(5, _translate("MainWindow", "400"))
        self.cbDpiTo.setItemText(6, _translate("MainWindow", "600"))
        self.cbDpiTo.setItemText(7, _translate("MainWindow", "1200"))
        self.label_7.setText(_translate("MainWindow", "dpi"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_5.setTitle(_translate("MainWindow", "Экспорт..."))
        self.menu_6.setTitle(_translate("MainWindow", "Импорт..."))
        self.menu_7.setTitle(_translate("MainWindow", "Обработать в каталоге"))
        self.menu_2.setTitle(_translate("MainWindow", "Разметка"))
        self.menu_3.setTitle(_translate("MainWindow", "Линия"))
        self.menu_4.setTitle(_translate("MainWindow", "Текст"))
        self.menu_8.setTitle(_translate("MainWindow", "Распознавание"))
        self.actOpenAndProcessImage.setText(_translate("MainWindow", "Разметить"))
        self.actOpenText.setText(_translate("MainWindow", "Текст..."))
        self.actOpenMarkup.setText(_translate("MainWindow", "Загрузить разметку..."))
        self.actSaveImage.setText(_translate("MainWindow", "Изображения"))
        self.actSaveBbox.setText(_translate("MainWindow", "Областей букв"))
        self.actSaveText.setText(_translate("MainWindow", "Текста"))
        self.actSaveMarkup.setText(_translate("MainWindow", "Сохранить разметку"))
        self.actExit.setText(_translate("MainWindow", "Выйти"))
        self.actChange1b1c.setText(_translate("MainWindow", "1b1c"))
        self.actChange2b1c.setText(_translate("MainWindow", "2b1c"))
        self.actChange3b1c.setText(_translate("MainWindow", "3b1c"))
        self.actChange1b2c.setText(_translate("MainWindow", "1b2c"))
        self.actChange1b3c.setText(_translate("MainWindow", "1b3c"))
        self.actTextLineSet.setText(_translate("MainWindow", "Установить строку и сбросить маркировку"))
        self.actTextLineUpdate.setText(_translate("MainWindow", "Обновить строку"))
        self.actTextEdit.setText(_translate("MainWindow", "Редактировать текст целиком..."))
        self.action_3.setText(_translate("MainWindow", "Изменить регион (box,char)"))
        self.action_box_char.setText(_translate("MainWindow", "Отделить регион (box,char)"))
        self.action_box_char_2.setText(_translate("MainWindow", "Объединить регионы (mu)"))
        self.actShowPageBase.setText(_translate("MainWindow", "Предпросмотр символов..."))
        self.actMarkupDefault.setText(_translate("MainWindow", "Разметить по умолчанию..."))
        self.actOpenBbox.setText(_translate("MainWindow", "Области букв..."))
        self.actSkipBoxLine.setText(_translate("MainWindow", "Пропустить область"))
        self.actSkipTextLine.setText(_translate("MainWindow", "Пропустить строку"))
        self.actOpenImage.setText(_translate("MainWindow", "Открыть изображение..."))
        self.actMuLineUp.setText(_translate("MainWindow", "Переместить регион вверх (box)"))
        self.actMuLineDown.setText(_translate("MainWindow", "Переместить регион вниз (box)"))
        self.actSaveSymbols.setText(_translate("MainWindow", "Сохранить символы"))
        self.actSelToUpLine.setText(_translate("MainWindow", "Перенести в верхнюю линию"))
        self.actSelToDownLine.setText(_translate("MainWindow", "Перенести в нижнюю линиию"))
        self.actSelExclude.setText(_translate("MainWindow", "Исключить выделенное"))
        self.actSelToNewLine.setText(_translate("MainWindow", "Перенести в новую линию"))
        self.actDelLine.setText(_translate("MainWindow", "Удалить линию"))
        self.actPathConvertMkpSmp.setText(_translate("MainWindow", "Извлечь и сохранить символы (mkp->smp)"))
        self.actCheckHyp.setText(_translate("MainWindow", "Проверка гипотез"))
        self.actBuildStatistics.setText(_translate("MainWindow", "Собрать статистику по разметке"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

